// components/menu/menu-links.vue
<template>
  <div>
    <NuxtLink href="/">
      <a className="m-2">ABOUT</a>
    </NuxtLink>
    <NuxtLink href="/music">
      <a className="m-2">MUSIC</a>
    </NuxtLink>
    <NuxtLink href="/contact">
      <a className="m-2">CONTACT</a>
    </NuxtLink>
  </div>
</template>

<script lang="ts" setup>
import about from '~/content/about.json';
</script>

<style lang="postcss" scoped></style>

// components/layout/MenuLinks.jsx
import React from 'react'
import Link from 'next/link'

const MenuLinks = ({ className }) => {
  return (
    <div className={className}>
      <Link href="/">
        <a className="m-2">ABOUT</a>
      </Link>
      <Link href="/music">
        <a className="m-2">MUSIC</a>
      </Link>
      <Link href="/contact">
        <a className="m-2">CONTACT</a>
      </Link>
    </div>
  )
}

export default MenuLinks
