// components/menu/index.vue
<template>
  <div>
    <div class="md:hidden ml-6 mt-6">
      <arrow-button
        v-if="isMenuOpen"
        :active="isMenuOpen"
        :handleClick="handleClick"
        :icon="ArrowLeft"
        :alt="hamburger - menu"
        :size="20"
      />
      <button v-else type="button" @click="handleClick">
        <img width="40" height="40" src="hamburgerIcon" alt="hamburger-menu" />
      </button>
    </div>

    <div v-if="isMenuOpen" class="md:hidden bg-white">
      <menu-links class="flex flex-col items-center" />
    </div>

    <div class="w-full hidden md:inline-block font-light text-xl my-4">
      <menu-links class="flex flex-row items-center justify-evenly" />
    </div>
  </div>
</template>

<script lang="ts" setup>
// import hamburgerIcon from '~/assets/hamburger.svg';

const isMenuOpen = ref<boolean>(false);

const handleClick = (): void => {
  isMenuOpen.value = !isMenuOpen.value;
};
</script>

<style lang="postcss" scoped></style>

// components/layout/Menu.jsx
import React, { useState } from 'react'
import Image from 'next/image'
import hamburgerIcon from '../../public/assets/hamburger.svg'
import ArrowLeft from '../../public/assets/arrow-left.svg'
import ArrowButton from '../common/ArrowButton'
import MenuLinks from './MenuLinks'

const Menu = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false)

  const handleClick = () => {
    setIsMenuOpen(!isMenuOpen)
  }

  return (
    <>
      <div className="md:hidden ml-6 mt-6">
        {isMenuOpen ? (
          <ArrowButton
            active={isMenuOpen}
            handleClick={handleClick}
            icon={ArrowLeft}
            alt="hamburger-menu"
            size={20}
          />
        ) : (
          <button onClick={handleClick}>
            <Image
              width={40}
              height={40}
              src={hamburgerIcon}
              alt="hamburger-menu"
            />
          </button>
        )}
      </div>

      {isMenuOpen && (
        <div className="md:hidden bg-white">
          <MenuLinks className="flex flex-col items-center" />
        </div>
      )}

      <div className="w-full hidden md:inline-block font-light text-xl my-4">
        <MenuLinks className="flex flex-row items-center justify-evenly" />
      </div>
    </>
  )
}

export default Menu
