// components/common/ArrowButton.jsx
import Image from 'next/image'
import React from 'react'

const ArrowButton = ({ handleClick, icon, alt, size, className, active }) => {
  return (
    <>
      {active && (
        <button onClick={handleClick} className={className}>
          <Image width={size} height={size} src={icon} alt={alt} />
        </button>
      )}
    </>
  )
}

export default ArrowButton

// components/arrow-button/index.vue
<template>
  <template v-if="active">
    <button type="button" @click="handleClick">
      <img :width="size" :height="size" :src="icon" :alt="alt" />
    </button>
  </template>
</template>

<script lang="ts" setup>
import about from '~/content/about.json';

defineProps({
  handleClick: { type: Object as () => void, required: true },
  icon: Object,
  alt: String,
  size: Number,
  active: Boolean,
});
</script>

<style lang="postcss" scoped></style>
